(when (require-package 'web-mode)
  (add-auto-mode 'web-mode "\\.phtml\\'")
  (add-auto-mode 'web-mode "\\.tpl\\.php\\'")
  (add-auto-mode 'web-mode "\\.tpl\\'")
  (add-auto-mode 'web-mode "\\.blade\\.php\\'")
  (add-auto-mode 'web-mode "\\.jsp\\'")
  (add-auto-mode 'web-mode "\\.as[cp]x\\'")
  (add-auto-mode 'web-mode "\\.erb\\'")
  (add-auto-mode 'web-mode "\\.html?\\'"))

(provide 'init-web)
